name: Workflow Filters and Activities

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - '!feature/*'    # like branches-ignore: feature/*
    # branches-ignore:
    #   - feature/*     # feature/add-music, feature/update-iamge
    #   - test/**       # test/ui/index, test/checkout/payment/
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:
      - README.md
    branches:
      - master

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: Workflow Filters
      run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}